<!DOCTYPE html>
<?php ob_start(); ?>
<?php require_once "cs/config.php"; ?>
<html lang="en">
	<head>
		<title>1Book</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="<?php echo $SiteURL;?>img/fevicon.ico" type="image/x-icon" />
		<link rel="stylesheet" href="<?php echo $SiteURL;?>css/bootstrap.min.css">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
		<link rel="stylesheet" href="css/common.css">
		<link rel="stylesheet" href="css/bookshelf.css">
		<link rel="stylesheet" href="css/responsive.css">
	</head>
	<body>
	<div class="mainWrap">
		
	   <!-- Header Start Here -->
	   <?php include_once('header.php');?>
	   <!-- Header End Here -->

		<div class="col-xs-12 padd0 divBG1" style="display:none;">
			<div class="innerWrap padd015">
				<div class="pull-left shelfTxt">Our Team</div>
				<div class="pull-right" style="display:none;">
					<form class="navbar-form searchBox1" role="search">
						<div class="input-group">
							<input type="text" class="form-control searchBoxInput" placeholder="Find eBook, eNotes, etc" name="q">
							<div class="input-group-btn">
								<button class="btn btn-default searchBoxBtn" type="submit"><i class="glyphicon glyphicon-search"></i></button>
							</div>
						</div>
					</form>
				</div>
				<div style="display: block; clear: both;"></div>
			</div>
		</div>
		

		<div class="col-xs-12 padd0 mtop20">
			<div class="innerWrap">
			    <h4 class="common_title">Terms of Use</h4>
				<p><strong>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</strong></p>
<p><strong>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of <a href="http://1book.in/">www.1book.in</a> website.&nbsp;</strong></p>
				<p>The domain name www.1book.in (hereinafter referred to as &quot;Website&quot;) is&nbsp;owned by Onlybook Educational Technologies Private Limited a company incorporated under the Companies Act, 2013 with its registered office at 601, Technology Apartments, I.P. Extension, Delhi-110092 (hereinafter referred to as &quot;1Book&quot;).</p>
<p><!--[endif]--><o:p></o:p></p>
<p>Your use of the 1Bookstore, Dashboard and other tools (collectively &ldquo;Services&rdquo;) included in Website are governed by the following&nbsp;terms and conditions<strong> (&quot;Terms of Use&quot;)</strong> as applicable to the Website including&nbsp;the applicable policies which are incorporated herein by way of reference. If You&nbsp;transact on the Website, You shall be subject to the policies that are applicable&nbsp;to the Website for such transaction. By mere use of the Website, You shall be&nbsp;contracting with Onlybook Educational Technologies Private Limited and these terms and conditions including the policies constitute your binding obligations.<o:p></o:p><br />
<!--[endif]--><o:p></o:p></p>
<p>For the purpose of these Terms of Use, wherever the context so requires&nbsp;<strong>&quot;You&quot;&nbsp;or&nbsp;&quot;User&quot;&nbsp;</strong>shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as&nbsp;Registered User or otherwise using the computer systems. &ldquo;You&rdquo; or &ldquo;User&rdquo; shall also include the person providing,using and/or uploading content on 1Book website, whether for the purpose of sale or otherwise and includes seller, publisher, Content Provider, educator, professor, teacher or by whatever name called.<br />
<br />
The term&nbsp;<strong>&quot;We&quot;,&nbsp;&quot;Us&quot;,&nbsp;&quot;Our&quot;, &quot;1Book&quot;</strong>&nbsp;shall mean Onlybook Educational Technologies Private Limited.</p>
<p>When You use any of the services provided by Us through the Website, You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service,&nbsp;and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our&nbsp;sole discretion, to change, modify, add or remove portions of these Terms of Use,&nbsp;at any time without any prior written notice to You. It is Your responsibility to&nbsp;review these Terms of Use periodically for updates / changes. Your continued use&nbsp;of the Website following the posting of changes will mean that You accept and&nbsp;agree to the revisions. As long as You comply with these Terms of Use, We grant&nbsp;You a personal, non-exclusive, non-transferable, limited privilege to enter and&nbsp;use the Website.</p>
<p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES&nbsp;YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE&nbsp;PROCEEDING.</strong>&nbsp;By impliedly or expressly accepting these Terms of Use, You also&nbsp;accept and agree to be bound by 1Book Policies ((including but not limited to&nbsp;Privacy Policy available at&nbsp;Privacy) as amended&nbsp;from time to time.</p>
<p><strong>Your Account and Registration Obligations</strong></p>
<p>If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.</p>
<p><strong>Communications</strong></p>
<p>When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.</p>
<p><strong>Platform for Transaction and Communication</strong></p>
<p>This Website is a platform that users utilise to meet and interact with one another for their transactions.&nbsp;</p>
<p>The commercial / contractual terms include without limitation price, shipping costs, date, period, mode of delivery, warranties related to products and services including after sales services related to products and services, etc., and the same may be subject to change. The agreement between you and 1Book is subject to the following terms and conditions:-</p>
<p>Henceforward:</p>
<p>1. You certify that you are at least 18 (eighteen) years of age or has the consent of a parent or legal guardian.</p>
<p>2. These terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the Shopping services of 1Book you agree to be bound by the Terms and Conditions.</p>
<p>3. By indicating Your acceptance to purchase any product or service offered on the Website, you are obligated to complete such transactions. You shall prohibit from indicating your acceptance to purchase products and services where you do not intend to complete such transactions.</p>
<p>4. Any order placed for a product that is listed at an incorrect price may be cancelled. This shall be regardless of whether the order has been confirmed and/or payment levied. In the event the payment has been processed, the same shall be credited to your account and duly notified to you by email.</p>
<p>5. In a credit card transaction, you must use your own credit card. 1Book will not be liable for any credit card fraud. The liability to use a card fraudulently will be on the user and the onus to 'prove otherwise' shall be exclusively on the user.</p>
<p>6. The User agrees to use the services provided by 1Book, its affiliates, consultants and contracted companies, for lawful purposes only. Company may assign any or all of its rights under these Terms to its Affiliates without consent of the User.</p>
<p>7. In the event of non-delivery of the products to the customers, 1Book's liability shall be limited only to the refund of the exact amount paid by the customer for the purchase of the product</p>
<p>8. 1Book's liability to any claims will only be up to and limited to the cost of the product units in question.</p>
<p><strong>Disclaimer:</strong> Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, the said amount will be reversed back in your Card Account.</p>
<p>9. In case we receive a cancellation notice and the order has not been processed/approved by us, we shall cancel the order and refund the entire amount. We will not be able to cancel orders that have already been processed and provided by us. We have the full right to decide whether an order has been processed or not. The customer agrees not to dispute the decision made by us and accept our decision regarding the cancellation &amp; non-payment.</p>
<p>10. You release and indemnify 1Book and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, 1Book cannot take responsibility or control the information provided by other Users which is made available on the Website. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.</p>
<p>11. We may, from time to time, restrict access to certain features, parts or content of the Website or a Product, or the entire Website or Services, to users who have registered with us. You must ensure that any registration details you provide are accurate and you must keep those details accurate and up to date. &nbsp; You agree that 1Book may, at any time and with or without prior notice, remove Licensed Content from the Service or Website if we determine, in our sole discretion, that we do not possess the appropriate or necessary rights to provide you with access to such Licensed Content. In the event 1Book elects to remove Licensed Content from the Service AND SUCH REMOVAL OCCURS WITHIN THE FIRST 12 MONTHS FOLLOWING YOUR DATE OF PURCHASE, you agree that your sole and exclusive remedy shall be a refund of all amounts previously paid by you to 1Book for the removed Licensed Content. IN THE EVENT 1BOOK ELECTS TO REMOVE LICENSED CONTENT FROM THE SERVICE AT ANY TIME AFTER 12 MONTHS FROM YOUR DATE OF PURCHASE OF SUCH LICENSED CONTENT, YOU AGREE THAT YOU SHALL NOT BE ENTITLED TO ANY REFUND FROM 1BOOK.</p>
<p>Please note that there could be risks in dealing with underage persons or people acting under false pretence.</p>
<p><strong>Charges</strong></p>
<p>Membership on the Website is free for buyers. 1Book does not charge any fee for browsing on the Website. 1Book reserves the right to change its Fee Policy from time to time. In particular, 1Book may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event 1Book reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Onlybook Educational Technologies Private Limited.</p>
<p><strong>Use of the Website</strong></p>
<p>You agree, undertake and confirm that Your use of Website shall be strictly governed by the following binding principles:</p>
<p>&nbsp;1. You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>
<div>(a) belongs to another person and to which You does not have any right to;</div>
<p>(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to &quot;indecent representation of women&quot; within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>
<p>(c) is misleading in any way;</p>
<p>(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;</p>
<p>(e) harasses or advocates harassment of another person;</p>
<p>(f) involves the transmission of &quot;junk mail&quot;, &quot;chain letters&quot;, or unsolicited mass mailing or &quot;spamming&quot;;</p>
<p>(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;</p>
<p>(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];</p>
<p>(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see &quot;Copyright complaint&quot; below for instructions on how to lodge a complaint about uploaded copyrighted material);</p>
<p>(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</p>
<p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>
<p>(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</p>
<p>(m) contains video, photographs, or images of another person (with a minor or an adult).</p>
<p>(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</p>
<p>(o) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;</p>
<p>(p) interferes with another USER's use and enjoyment of the Website or any other individual's User and enjoyment of similar services;</p>
<p>(q) refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</p>
<p>(r) harm minors in any way;</p>
<p>(s) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent;</p>
<p>(t) violates any law for the time being in force;</p>
<p>(u) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
<p>(v) impersonate another person;</p>
<p>(w) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p>
<p>(x) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</p>
<p>(y) shall not be false, inaccurate or misleading;</p>
<p>(z) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.</p>
<p>(aa) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider (&quot;ISPs&quot;) or other suppliers;</p>
<p>2. You shall not use any &quot;deep-link&quot;, &quot;page-scrape&quot;, &quot;robot&quot;, &quot;spider&quot; or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve Our right to bar any such activity.</p>
<p>3. You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password &quot;mining&quot; or any other illegitimate means.</p>
<p>4. You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.</p>
<p>5. You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms 1Book, Onlybook, 1Book.in, or otherwise engage in any conduct or action that might tarnish the image or reputation, of 1Book or sellers on platform or otherwise tarnish or dilute any 1Book's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or 1Book's systems or networks, or any systems or networks connected to 1Book.</p>
<p>6. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website.</p>
<p>7. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</p>
<p>8. You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of 1Book and / or others.</p>
<p>9. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.</p>
<p>10. Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.</p>
<p>11. From time to time, You shall be responsible for providing information relating to the products/services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.</p>
<p>12. You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products/services, including, but not limited to, products or services related to that being displayed on the Website or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Website. It shall be a violation of these Terms of Use to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to protect Our Users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other Users in any 24-hour period which We deems appropriate in its sole discretion. You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.</p>
<p>We reserve the right, but has no obligation, to monitor the materials posted on the Website. 1Book shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect 1Book views. In no event shall 1Book assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information.</p>
<p>13. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Website, including payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Website.</p>
<p>14. It is possible that other users (including unauthorized users or &quot;hackers&quot;) may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We does not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.</p>
<p>15. 1Book shall have all the rights to take necessary action (including appropriate legal action) and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</p>
<p><strong>Contents Posted on Website</strong></p>
<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, &quot;Content&quot;), is a third party user generated content and 1Book has no control over such third party user generated content as 1Book is merely an intermediary for the purposes of this Terms of Use.</p>
<p>Except as expressly provided in these Terms of Use, no part of the Website and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including &quot;mirroring&quot;) to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without 1Book's express prior written consent.</p>
<p>You may use information on the products and services purposely made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.</p>
<p>You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Website (collectively, &quot;Content&quot;). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Website as mentioned herein, and You are not entitled to any payment or other compensation for such use.</p>
<p><strong>Privacy</strong></p>
<p>We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at Privacy. If You object to Your Information being transferred or used in this way please do not use Website.</p>
<p>We may share personal information with our other corporate entities and affiliates. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out.</p>
<p>We may disclose personal information to third parties. This disclosure may be required for us to provide you access to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.</p>
<p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>
<p>We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.</p>
<p><strong>Disclaimer of Warranties and Liability</strong></p>
<p>This Website, all the products and services, included on or otherwise made available to You through this Website are provided on &quot;as is&quot; basis without any representation or warranties, express or implied except otherwise specified in writing.&nbsp;</p>
<p>Without prejudice to the forgoing paragraph, 1Book does not warrant that:</p>
<p>&bull; This Website will be constantly available, or available at all; or</p>
<p>&bull; The information on this Website is complete, true, accurate or non-misleading.</p>
<p>1Book will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website. 1Book does not warrant that this Website; information, Content, product or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.</p>
<p>Nothing on Website constitutes, or is meant to constitute, advice of any kind. &nbsp;</p>
<p>You may be required to enter a valid phone number while placing an order on the Website. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.</p>
<p><strong>Selling</strong></p>
<p>As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website.&nbsp;</p>
<p>The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. 1Book reserves the right to delete such multiple listings of the same product listed by you in various categories.</p>
<p><strong>Terms of Sale to Buyer</strong></p>
<p>1Book makes available Digital Content for purchase by you through the 1Book Store (each content item designated as such by 1Book, an &quot;Item&quot;). Prices are displayed with the applicable Item. Prices and availability of all Items are subject to change at any time. 1Book reserves the right to discontinue or suspend the provision of any Item at any time.&nbsp;</p>
<p>While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</p>
<p>1. Lack of authorization for any transaction/s, or</p>
<p>2. Exceeding the present limit mutually agreed by You and between &quot;Bank/s&quot;, or</p>
<p>3. Any payment issues arising out of the transaction, or</p>
<p>4. Decline of transaction for any other reason/s</p>
<p>All payments made against the purchases/services on Website by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Website will not facilitate transaction with respect to any other form of currency with respect to the purchases made on Website.</p>
<p>In the event of non-delivery of the products to the customers, 1Book&rsquo;s liability shall be limited only to the refund of the exact amount paid by the customer for the purchase of the product.</p>
<p><strong>Payment Facility for Buyers:</strong></p>
<p>1. You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract to purchase the products and /or services using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank &nbsp;using Payment Facility.</p>
<p>2. You, as a Buyer, shall electronically notify Payment Facility using the appropriate 1Book Website features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within fifteen (15) days shall be construed as a deemed Delivery in respect of that Transaction.&nbsp;</p>
<p>3. You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within fifteen (15) days, whichever is earlier. In case you do not raise a refund claim using Website features within the stipulated time than this would make You ineligible for a refund.</p>
<p>4. Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.</p>
<p>5. For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India (RBI).</p>
<p>6. Refund shall be conditional and shall be with recourse available to 1Book in case of any misuse by Buyer.</p>
<p>7. Refund shall be subject to Buyer complying with Policies.</p>
<p>8. You must provide valid credit card billing information or other payment information to purchase a license to an Item. You agree that 1Book may charge fees to your credit card or other payment account for licenses to Items that you purchase and that you will pay all applicable fees assessed to your Account. Our prices are exclusive of all taxes, levies, or duties imposed by taxing authorities, and you are responsible for payment of all such taxes, levies and duties.&nbsp;</p>
<p>9. In the event of a conflict between the prices displayed for any Item, the price shown at the time you check out your order will be the price charged to you.&nbsp;</p>
<p>10. 1Book is not responsible for pricing errors; however, if the price you pay for an Item is higher than its true price, 1Book, in its sole discretion, may grant you a credit or refund for the amount exceeding the true price. On occasion, technical problems may prevent or unreasonably delay download of the Item for which you have purchased a license hereunder, in which case your sole and exclusive remedy will either be replacement or refund of the price paid, as determined by 1Book. Upon your download of an Item, you are responsible for any loss, damage, or deletion of that Item and 1Book will have no liability to you for any loss, damage, or deletion of that Item.&nbsp;</p>
<p>11. You grant 1Book the right to disable access to any Item or remotely remove that Item from your 1Book Account and expressly consent to such disablement or removal, provided that 1Book will not exercise such right unless you return the applicable Item. Each Item is deemed irrevocably accepted fifteen (15) days after download thereof.</p>
<p>12. 1Book reserves the right to impose limits on the number of Transactions or Transaction Price which 1Book may receive from on an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual Buyer during any time period, and reserves the right to refuse to process Transactions exceeding such limit.</p>
<p>13. 1Book reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any agreements by Buyer with 1Book or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</p>
<p>14. 1Book may do such checks as it deems fit before approving the receipt of/Buyers commitment to pay (for Cash On Delivery transactions) Transaction Price from the Buyer for security or other reasons at the discretion of 1Book. As a result of such check if 1Book is not satisfied with the creditability of the Buyer or genuineness of the Transaction / Transaction Price, it will have the right to reject the receipt of / Buyers commitment to pay Transaction Price.</p>
<p>15.The Buyer and Seller acknowledge that 1Book will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond control of 1Book.</p>
<p><strong>Compliance with Laws:</strong></p>
<p>16. Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made thereunder, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and 1Book Website.</p>
<p><strong>Buyer's arrangement with Issuing Bank:</strong></p>
<p>17. All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.</p>
<p>18. All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.</p>
<p>Without limiting the Disclaimer of Warranties and Limitation of Liability in this terms of use, in no event shall our or our and/or our Digital Content providers' total liability to You for all damages arising from your use of the Service, the Digital Content, or information, materials or products included on or otherwise made available to You through the Service, exceed the amount You paid to purchase, on the Service, the Digital Content related to Your claim for damages.</p>
<p><strong>4. Proprietary Rights</strong></p>
<p><strong>4.1 Use of the 1Book Service.</strong> &nbsp;Subject to the terms and conditions of this Agreement, 1Book grants you, during the term of this Agreement, permission to access and use the 1Book Service solely for your personal, non-commercial purposes.</p>
<p><strong>4.2 Use of Items.</strong> &nbsp;Subject to the terms and conditions of this Agreement and the payment of all applicable fees for the Item, 1Book grants you a non-exclusive, non-transferable, revocable license to download and use each Item in accordance with the Usage Rules posted on the 1Book Store solely for your personal, non-commercial purposes as part of the 1Book Service during the period designated for such Item on the 1Book Store. Additional terms relating to the Items may be posted on the 1Book Store. Usage Rules may include limitations on the rental period, your ability to cut, copy and paste, or print portions of an Item, the number of applications from which you can access an Item, geographic territories, and reading aloud functionality.</p>
<p><strong>4.3 Restrictions. </strong>&nbsp;You will not: (a) permit any third party to access or use the 1Book Store or 1Book Service using your 1Book Account; (b) rent, lease, loan, sell, license, or transfer the 1Book Store or 1Book Service to any third party or exploit the 1Book Store or 1Book Service for commercial purposes; or (c) remove or modify any proprietary notices or labels on any Item.</p>
<p><strong>4.4 Ownership. </strong>&nbsp;1Book own the 1Book Store and all intellectual property rights relating to the foregoing. Any unauthorized reproduction, modification, distribution, transmission, display, or performance of any portion of the 1Book Store, the Items, or any other content (except for your User Content and Public Content) contained in the 1Book Store or 1Book Service is strictly prohibited. 1Book and its licensors reserve all rights not expressly granted under this Agreement. There are no implied licenses in this Agreement. Despite any use of the terms &ldquo;purchase,&rdquo; &ldquo;buy,&rdquo; &ldquo;sell,&rdquo; &ldquo;sale,&rdquo; or similar terms, all Items and the applicable copies thereof are licensed to you under this Agreement, not sold.</p>
<p><strong>4.5 Feedback. </strong>&nbsp;By providing comments, suggestions, and other feedback current and future products and services (collectively, &quot;Feedback&quot;), you grant to an irrevocable, non-exclusive, royalty-free and fully paid, worldwide, transferable license, with the right to sublicense through multiple tiers, to reproduce, distribute, modify, publicly display, publicly perform, prepare derivative works of, transmit, and otherwise use and exploit such Feedback, in any format or medium now 1Book own or developed in the future, for any purpose and in any manner. 1Book will have no obligation to compensate you in connection with any Feedback.</p>
<p><strong>5. Interaction with Other Users. </strong>&nbsp; You are solely responsible for your interactions with other users. 1Book reserves the right, but has no obligation, to monitor or take any action regarding disputes between you and other users. To the extent permitted under applicable law, you hereby release 1Book from any and all claims or liability related to: (a) any content posted on the 1Book Website; or (b) the conduct, whether online or offline, of any other user.</p>
<p>WARRANTY DISCLAIMER</p>
<p>YOU AGREE THAT 1BOOK IS NOT RESPONSIBLE FOR ANY FAILURE TO BACK UP ANY PORTION OF ITEMS DOWNLOADED BY YOU OR YOUR USER CONTENT OR PUBLIC CONTENT. 1BOOK DOES NOT ASSUME ANY OBLIGATION TO MONITOR ACTIVITIES CONDUCTED ON THE 1BOOK WEBSITE.</p>
<p><strong>Limitation of Liability. &nbsp;</strong>&nbsp;</p>
<p>TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, (A) 1BOOK WILL NOT BE LIABLE FOR ANY LOSS OF USE OR LOST PROFITS OR INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES RELATING TO THE 1BOOK SERVICES OR OTHERWISE IN CONNECTION WITH THIS AGREEMENT, EVEN IF 1BOOK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND (B) 1BOOK&rsquo;S TOTAL CUMULATIVE LIABILITY IN CONNECTION WITH THE 1BOOK WEBSITE , SERVICES AND ANY OTHER INFORMATION AND CONTENT ON THE 1BOOK WEBSITE.</p>
<p><strong>Indemnity</strong></p>
<p>You shall indemnify and hold harmless 1Book, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
<p><strong>Applicable Law</strong></p>
<p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Delhi.</p>
<p><strong>Jurisdictional Issues/Sale in India Only</strong></p>
<p>Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. 1Book make no representation that materials in the Website are appropriate or available for use in other locations/Countries other than India. Those who choose to access this Website from other locations/Countries other than India do so on their own initiative and 1Book is not responsible for supply of products/refund for the products ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.</p>
<p><strong>Trademark, Copyright and Restriction</strong></p>
<p>This Website is controlled and operated by Onlybook Educational Technologies Private Limited. All material on this Website, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on Website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>
<p><strong>Trademark complaint</strong></p>
<p>1Book respects the intellectual property of others. In case You feel that Your Trademark has been infringed, You can write to 1Book at <a style="color:blue" href="mailto:1booktechteam@gmail.in" target="_top">1booktechteam@gmail.in</a>.</p>
<p><strong>Product Description</strong></p>
<p>1Book we do not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>
<p><strong>Limitation of Liability</strong></p>
<p>IN NO EVENT SHALL 1BOOK BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>
<p><strong>Contact Us&nbsp;</strong></p>
<p>Please contact us for any questions or comments or any other communication regarding this Website.</p>
<p><strong>Grievance officer</strong></p>
<p>In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:Mr. Rajat Nandwani</p>
<p>Onlybook Educational Technologies Private Limited.</p>
<p>601, Technology Apartments,&nbsp;</p>
<p>I.P. Extension</p>
<p>New Delhi, India</p>
<p>Phone: +91&ndash;9999249105&nbsp;</p>
<p>Email: rajatnandwani1991@gmail.com</p>
<p>Time: Mon - Fri (9:00 am- 6:00 pm)</p>
<p><strong>POLICIES</strong></p>
<p><strong>Profanity Policy</strong></p>
<p>1Book prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.</p>
<p>This policy extends to text within listings, on Seller pages and all other areas of the Website that another User may view. If the profane words are part of a title for the item being sold, we allow Sellers to 'blur' out the bulk of the offending word with asterisks (i.e., s*** or f***).</p>
<p>Please report any violations of this policy to the correct area for review:</p>
<p>&bull; Report offensive Display Names</p>
<p>&bull; Report offensive language in a listing or otherwise</p>
<p>If a feedback comment; or any communication made between Users on the Website; or email communication between Users in relation to transactions conducted on Website contain profanity, please review Our feedback removal policy and submit a request for action/removal.</p>
<p>Disciplinary action may result in the indefinite suspension of a User's account, temporary suspension, or a formal warning.</p>
<p>1Book will consider the circumstances of an alleged policy violation and the user's trading records before taking action.</p>
<p>Violations of this policy may result in a range of actions, including:</p>
<p>1. Limits placed on account privileges;</p>
<p>2. Loss of special status;</p>
<p>3. Account suspension.</p>
<p><strong>1Book Infringement Verification - Reporting Listing Violations</strong></p>
<p>1Book has put in place 1Book Infringement Verification process so that intellectual property owners could easily report listings that infringe their rights. It is in 1Book's interest to ensure that infringing products are removed from the Website, as they erode Buyer and good Seller trust.</p>
<p>&bull; Only the intellectual property rights owner can report potentially infringing products or listings. If you are not the intellectual property rights owner, you can still help by getting in touch with the rights owner and encouraging them to contact us.</p>
<p>&bull; If your listing was removed, and you believe that your listing was removed in error, please contact us.</p>
<p>1Book does not and cannot verify that Sellers have the right or ability to sell or distribute their listed products. However, 1Book is committed to removing infringing or unlicensed products once an authorized representative of the rights owner properly reports them to 1Book.</p>
<p>1Book works to ensure that item listings do not infringe upon the copyright, trademark or other intellectual property rights of third parties.&nbsp;</p>
<p><strong>Notice of Infringement</strong></p>
<p>Onlybook Educational Technologies Private Limited</p>
<p>&nbsp;_______________________</p>
<div>_______________________</div>
<div>I, [name] ____________________________ of [address] _________________________ do solemnly and sincerely declare as follows:</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>1. I am the owner of certain intellectual property rights, said owner being named __________________ (&quot;IP Owner&quot;).</div>
<div>2. I have a good faith belief that the item listings or materials identified in the annexure attached hereto are not authorised by the above IP Owner, its agent, or the law and therefore infringe the IP Owner's rights. Please expeditiously remove or disable access to the material or products claimed to be infringing.</div>
<div>3. I may be contacted at:</div>
<div>Name ___________________________________________________________</div>
<div>Title &amp; Company ________________________________________________________</div>
<div>Address _________________________________________________________</div>
<div>Email (correspondence) ___________________________________________________</div>
<div>Telephone/Fax _____________________________________________________________</div>
<div>Date _________________________________________________________________</div>
<div>and I make this declaration conscientiously believing it to be true and correct.</div>
<div>Declared by ______________________________</div>
<div>on [date] ___________________________________ in [place]________</div>
<div>Truthfully,</div>
<div>Signature</div>
<p></p>
<p><strong>Addendum to Notice of Infringement:</strong></p>
<p>List of Allegedly Infringing Listings.</p>
<p>A Note on Reason Codes: When identifying item numbers please use the reasons below. When removing products from the Website, 1Book will inform Sellers of the specific reason for the removal of their products.</p>
<p>Select the most appropriate reason. Please associate each item you report with only one reason code.</p>
<p><strong>Trademark-infringement</strong></p>
<p>1. Trademark owner doesn't make this type of product or has discontinued the production of the product</p>
<p>2. Item(s) is an unlawful replica of a product made by the trademark owner or is counterfeit</p>
<p><strong>Trademark-listing description infringement</strong></p>
<p>3. Listing(s) has unlawful comparison to trademark owner's brand or product</p>
<p>4. Listing(s) contains unlawful use of trademark owner's logo</p>
<p><strong>Copyright-item infringement</strong></p>
<p>5. Item(s) is an unlawful copy;</p>
<p>6. Item(s) is unlawful duplication of printed material</p>
<p><strong>Copyright-listing content infringement</strong></p>
<p>9. Listing(s) comprises unauthorized copy of copyrighted text</p>
<p>10. Listing(s) comprises unauthorized copy of copyrighted image</p>
<p>11. Listing(s) comprises unauthorized copy of copyrighted image and text</p>
<p>Reason Code: _____________________________________________________________</p>
<p>Work(s)</p>
<p>infringed: _________________________________________________________</p>
<p>Item Number(s): ___________________________________________________________</p>
<p>Note:</p>
<p>1. Please provide the ownership of Trademark (Trademark Registration Certificate should be in the name of applicant)</p>
<p>2. Please provide the evidence as to the ownership of copyright.</p>
<p>All such Notices of Infringement shall be sent to <a style="color:blue" href="mailto:1booktechteam@gmail.com" target="_top">1booktechteam@gmail.com</a>.</p>

			</div>
		</div>

	   <!-- Footer Start Here -->
	   <?php include_once('footer.php');?>
	   <!-- Footer End Here -->

	</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="js/index.js"></script>
		
		<script src="js/scrolltofixed.js"></script> <!-- plugin is used to fix elements on the page (top, bottom, anywhere) -->
	 
		<script>
		/* Fixed footer until it reaches its original position */
		$(document).ready(function() {
		$(".stickyNav").scrollToFixed();
		 
		$(window).scroll(function() {
		if ($(this).scrollTop() > 0) { // this refers to window
		$(".stickyNav").css("box-shadow", "0 2px 10px #999");
		}else{
		$(".stickyNav").css("box-shadow", "none");
		}
		});
		});
		/* Fixed footer until it reaches its original position */
		</script>
		
	</body>
</html>
<?php ob_end_flush(); ?>